Making changes to files in attempt to get docker working in wsl.

diff --git a/behat b/behat
--- a/behat
+++ b/behat
@@ -1,6 +1,29 @@
 #!/bin/bash
 
-function runbehat {
+function docker {
+    export TAGS=@$a
+    if [ ! -d "$MOODLE_DOCKER_WWWROOT" ];
+    then
+        echo 'Error: $MOODLE_DOCKER_WWWROOT is not set or not an existing directory'
+        exit 1
+    fi
+    DOCKERDIR="${MOODLE_DOCKER_WWWROOT}/moodle-docker"
+    if [ "$1" = "drop" ];
+    then
+        echo "dropping tests"
+        $DOCKERDIR/bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/util.php --drop
+        exit 0
+    fi
+
+    if [ "$2" = "rerun" ];
+    then
+        $DOCKERDIR/bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php --tags=$TAGS --rerun
+        exit 0
+    fi
+    $DOCKERDIR/bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php --tags=$TAGS
+}
+
+function travis {
     export TAGS=@$a
     if [ -z "$PARALLELRUNS" ]; then
         echo "running single behat test thread"
@@ -14,18 +37,9 @@ function runbehat {
         FROMRUN=$(($TORUN-$PARALLELPERNODE+1))
         php $DIR/admin/tool/behat/cli/run.php --tags=$TAGS --fromrun=$FROMRUN --torun=$TORUN --profile='firefox_{runprocess}' --replace='{runprocess}'
         exitcode=${PIPESTATUS[0]}
-        if [ "$MOODLEVERSION" = "313" ]; then
-            php $DIR/moodlescripts/get_behat_tests.php /home/travis/moodledata_behat $FROMRUN $TORUN ${exitcode}
-            exitcode=${PIPESTATUS[0]}
-        fi
         if [ "${exitcode}" -gt 0 ]; then
-            if [ "$MOODLEVERSION" = "313" ]; then
-                echo "re-running tests"
-                rerunbehat
-            elif [ "$MOODLEVERSION" = "341" ]; then
-                php $DIR/admin/tool/behat/cli/run.php --tags=$TAGS --fromrun=$FROMRUN --torun=$TORUN --profile='firefox_{runprocess}' --replace='{runprocess}' --rerun
-                exitcode=${PIPESTATUS[0]}
-            fi
+            php $DIR/admin/tool/behat/cli/run.php --tags=$TAGS --fromrun=$FROMRUN --torun=$TORUN --profile='firefox_{runprocess}' --replace='{runprocess}' --rerun
+            exitcode=${PIPESTATUS[0]}
             kill -9 $(lsof -ti tcp:4444)
             exit $exitcode
         else
@@ -35,20 +49,16 @@ function runbehat {
     fi
 }
 
-function rerunbehat {
-    echo "re-running failed tests"
-    if [ -s "rerun.txt" ]; then
-        cat rerun.txt
-        while read -r line || [[ -n "$line" ]];
-        do
-            ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/behatrun$line
-            $DIR/vendor/bin/behat --config $BEHAT_DATAROOT$line/behat/behat.yml --profile="firefox_$line" --tags=$TAGS --rerun
-            exitcode=${PIPESTATUS[0]}
-            if [ "${exitcode}" -gt 0 ]; then
-                kill -9 $(lsof -ti tcp:4444)
-                exit $exitcode
-            fi
-        done < "rerun.txt"
+function runbehat {
+    # For non-travis builds, run commands in docker
+    if [ -z "$TRAVIS_BUILD_DIR" ]; then
+        export DIR=/vagrant
+        export YMLDIR=/b_moodledata/behat
+        docker
+    else
+        export DIR=$TRAVIS_BUILD_DIR
+        export YMLDIR=/home/travis/roots/behatdata/behat
+        travis
     fi
 }
 
@@ -60,16 +70,6 @@ function translate_testtype {
 }
 
 PHP=$(type -p php)
-# For non-travis builds, start the jar and xvfb
-if [ -z "$TRAVIS_BUILD_DIR" ]; then
-    export DIR=/vagrant
-    export YMLDIR=/b_moodledata/behat
-    start_selenium 1
-else
-    export DIR=$TRAVIS_BUILD_DIR
-    export YMLDIR=/home/travis/roots/behatdata/behat
-fi
-
 # Check $1 for type of tests, otherwise use the diff.
 if [ -z "$1" ]; then
     export PLUGINS=$($PHP -f $DIR/moodlescripts/get_diff.php)
diff --git a/phpu b/phpu
--- a/phpu
+++ b/phpu
@@ -1,24 +1,46 @@
 #!/bin/bash
 
+function docker {
+    if [ ! -d "$MOODLE_DOCKER_WWWROOT" ];
+    then
+        echo 'Error: $MOODLE_DOCKER_WWWROOT is not set or not an existing directory'
+        exit 1
+    fi
+    DOCKERDIR="${MOODLE_DOCKER_WWWROOT}/moodle-docker"
+    if [ "$1" = "drop" ];
+    then
+        echo "dropping tests"
+        $DOCKERDIR/bin/moodle-docker-compose exec webserver php admin/tool/phpunit/cli/util.php --drop
+        exit 0
+    fi
+
+    cd $DIR
+    $DOCKERDIR/bin//moodle-docker-compose exec webserver vendor/bin/phpunit -c $TESTTYPE
+    cd -
+}
+
+function runphpunit {
+    # For travis builds, use its home dir, otherwise use /vagrant
+    if [ -z "$TRAVIS_BUILD_DIR" ];
+    then
+        export DIR=/vagrant
+        docker
+    else
+        export DIR=$TRAVIS_BUILD_DIR
+        cd $DIR && vendor/bin/phpunit -c $TESTTYPE && cd -
+    fi
+}
+
 PHP=$(type -p php)
-
-# For travis builds, use its home dir, otherwise use /vagrant
-if [ -z "$TRAVIS_BUILD_DIR" ];
-then
-    export DIR=/vagrant
-else
-    export DIR=$TRAVIS_BUILD_DIR
-fi
-
 # Check $1 for type of tests, otherwise use the diff.
 if [ -z "$1" ]; then
     export PLUGINS=$($PHP -f $DIR/moodlescripts/get_diff.php)
     read -ra arr <<<"$PLUGINS"
     for a in "${arr[@]}"; do
         export TESTTYPE="$a"
-        cd $DIR && vendor/bin/phpunit -c $TESTTYPE && cd -
+        runphpunit
     done
 else
     export TESTTYPE=$1
-    cd $DIR && vendor/bin/phpunit -c $TESTTYPE && cd -
+    runphpunit
 fi
diff --git a/tests b/tests
--- a/tests
+++ b/tests
@@ -7,27 +7,28 @@ else
     export PARALLEL=$2
 fi
 
+if [ ! -d "$MOODLE_DOCKER_WWWROOT" ];
+then
+    echo 'Error: $MOODLE_DOCKER_WWWROOT is not set or not an existing directory'
+    exit 1
+fi
+DOCKERDIR="${MOODLE_DOCKER_WWWROOT}/moodle-docker"
+
 if [ "$1" = "phpunit" ];
 then
 	echo "resetting phpunit tests"
-	php /vagrant/admin/tool/phpunit/cli/init.php
-    php /vagrant/admin/tool/phpunit/cli/util.php --buildcomponentconfigs
+    $DOCKERDIR/bin/moodle-docker-compose exec webserver php admin/tool/phpunit/cli/init.php
+    $DOCKERDIR/bin/moodle-docker-compose exec webserver php admin/tool/phpunit/cli/util.php --buildcomponentconfigs
 elif [ "$1" = "behat" ];
 then
 	echo "resetting behat tests"
     if [ "$PARALLEL" -gt 1 ];
     then
-        php /vagrant/admin/tool/behat/cli/init.php --parallel=$PARALLEL
+        $DOCKERDIR/bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/init.php --parallel=$PARALLEL
     else
-        php /vagrant/admin/tool/behat/cli/init.php
+        $DOCKERDIR/bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/init.php
     fi
-elif [ "$1" = "phpmd" ];
-then
-    echo "configuring phpmd"
-    cd /vagrant/phpmd
-    git submodule update --init --recursive
-    composer install
 else
-	echo "incorrect option given, use either phpunit|behat|phpmd"
+	echo "incorrect option given, use either phpunit|behat"
 fi
 
