Updating behat rerun to work with Moodle 3.4

diff --git a/behat b/behat
--- a/behat
+++ b/behat
@@ -13,14 +13,23 @@ function runbehat {
         TORUN=$(($CI_NODE_INDEX*$PARALLELPERNODE))
         FROMRUN=$(($TORUN-$PARALLELPERNODE+1))
         php $DIR/admin/tool/behat/cli/run.php --tags=$TAGS --fromrun=$FROMRUN --torun=$TORUN --profile='firefox_{runprocess}' --replace='{runprocess}'
-        php $DIR/moodlescripts/get_behat_tests.php /home/travis/moodledata_behat $FROMRUN $TORUN ${PIPESTATUS[0]}
+        if [ "$MOODLEVERSION" = "341" ]; then
+            echo "version 341, using rerun"
+            php $DIR/admin/tool/behat/cli/run.php --tags=$TAGS --fromrun=$FROMRUN --torun=$TORUN --profile='firefox_{runprocess}' --replace='{runprocess}' --rerun
+        else
+            php $DIR/moodlescripts/get_behat_tests.php /home/travis/moodledata_behat $FROMRUN $TORUN ${PIPESTATUS[0]}
+        fi
         exitcode=${PIPESTATUS[0]}
         if [ "${exitcode}" -gt 0 ]; then
-            echo "re-running tests"
-            rerunbehat
+            if [ "$MOODLEVERSION" = "313" ]; then
+                echo "re-running tests"
+                rerunbehat
+            fi
+            echo "a test failed"
             kill -9 $(lsof -ti tcp:4444)
             exit $exitcode
         else
+            echo "no failed tests"
             kill -9 $(lsof -ti tcp:4444)
             exit $exitcode
         fi
